# Supabase 项目配置

[project]
# 项目基本信息
name = "spider-mind"
id = "your-project-id"

[database]
# 数据库配置
port = 5432
shadow_port = 54321
major_version = 15

# 数据库池配置
[database.pooler]
enabled = false
port = 6543
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"
tenant_id = "realtime-dev"

[storage]
enabled = true
image_transformation_enabled = true

[auth]
enabled = true
# Auth 配置
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://your-domain.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

# SMTP 配置（可选，用于生产环境）
# [auth.email.smtp]
# host = "smtp.gmail.com"
# port = 587
# user = "your-email@gmail.com"
# pass = "your-app-password"
# admin_email = "your-email@gmail.com"
# sender_name = "Spider Mind"

[auth.sms]
enable_signup = false

[edge_runtime]
enabled = true
ip_version = "IPv4"

[functions]
verify_jwt = true

[analytics]
enabled = false