module.exports = {
  apps: [
    {
      name: 'dev-server',
      script: 'yarn',
      args: ['next', 'dev', '--turbo'],
      cwd: __dirname,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      log_file: './logs/dev-combined.log',
      out_file: './logs/dev-out.log',
      error_file: './logs/dev-error.log',
      log_date_format: 'MM-DD HH:mm:ss',
      depends_on: ['db-server', 'db-adminer'],
    },
    {
      name: 'db-server',
      script: 'docker',
      args: 'compose up postgres',
      cwd: __dirname,
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        COMPOSE_PROJECT_NAME: 'spider-mind',
      },
      log_file: './logs/db-combined.log',
      out_file: './logs/db-out.log',
      error_file: './logs/db-error.log',
      log_date_format: 'MM-DD HH:mm:ss',
    },
    {
      name: 'db-adminer',
      script: 'docker',
      args: 'compose up adminer',
      cwd: __dirname,
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        COMPOSE_PROJECT_NAME: 'spider-mind',
      },
      log_file: './logs/adminer-combined.log',
      out_file: './logs/adminer-out.log',
      error_file: './logs/adminer-error.log',
      log_date_format: 'MM-DD HH:mm:ss',
      depends_on: ['db-server'],
    },
  ],
}
